### ISSUE TITLE
Autosave option

### ISSUE THREAD

**Issue by muhammadnasr** [bietkul/react-reactive-form#34] opened 2019-02-14 10:39 UTC
Thanks for the great lib.

Do you have option for autosave like 

https://www.npmjs.com/package/react-distributed-forms

check the demo to see how it works.
https://codesandbox.io/s/5k30y1x05k

**Comment by bietkul** [comment] 2019-04-13 04:26
Hey, I think that is more like a React state implementation which can also be implemented with this library.
You can use `handleSubmit` function from control to make a form as submitted.
Refer docs: 
https://github.com/bietkul/react-reactive-form/blob/master/docs/api/FormGroup.md

**Comment by bietkul** [comment] 2019-04-24 07:39
It seems like the issue is not active anymore.
closing it, for now, feel free to re-open

**Closed by bietkul** 2019-04-24 07:39 UTC
