### ISSUE TITLE
re render FieldControl triger by state in react component

### ISSUE THREAD

**Issue by zokypesch** [bietkul/react-reactive-form#18] opened 2018-07-11 03:53 UTC
hii i have problem with fieldControll...

how to render fieldcontrol trigger by state in my own state,
example: 

this.state = {
            loginForm : FormBuilder.group({
                username: ["", Validators.required],
                nationality: ["", Validators.required],
            }),
            nationalityData: [] // <-- here
}

componentDidMount() {
ProductApi.product(this.props.token).then(function(product){
        let data = product.data.data
        let dataCbx = []
        
        data.forEach(value => dataCbx.push({value: value.prod_id, label: value.prod_name}));
        me.setState({nationalityData: dataCbx})

      });
}

}

render(){
  console.log(this.state.nationalityData); <---- data is comming not empty array
  return(
   <FieldGroup ........>
    render ....
   <FieldControl 
                      name="nationality" 
                      render={(obj) => this.ComboBox(obj)}
                      meta={{data: this.state.nationalityData}}
     />
  )
}

when axios was get data from my backend, it will be set a nationalityData but after set this, the combobox still have no data to show it. i make sure

**Comment by bietkul** [comment] 2018-07-11 07:18
Possible duplicate of 
https://github.com/bietkul/react-reactive-form/issues/10

**Closed by bietkul** 2018-07-11 07:18 UTC
Labels: duplicate
